### PR TITLE
Add ec2 creation on it

### PR DESCRIPTION
**Pull request by spcaipers-arm**

### CODE REVIEW

**Comment by spcaipers-arm** [comment]
Hi @MatthiasHertel80 should we create a v2?

**Comment by spcaipers-arm** [comment]
I have validated it with https://github.com/spcaipers-arm/VHT-GetStarted/pull/1 (which needs to merge back to the GetStarted!)

**Comment by spcaipers-arm** [comment]
FYI @JonatanAntoni

**Review by JonatanAntoni — APPROVED** [review]
LGTM. I guess you plan to add on-demand bucket creation in another PR?
Or do we want to move this effort into the Python implementation?

**Pull request merged**
